spring.application.name=session12

# datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/session12
spring.datasource.username=postgres
spring.datasource.password=S1mpL0rd

# jpa
spring.jpa.hibernate.ddl-auto=update