spring.application.name=session12

# datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/session12
spring.datasource.username=postgres
spring.datasource.password=S1mpL0rd

# jpa
spring.jpa.hibernate.ddl-auto=update

# logging level
logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.com.ra.session12.service=DEBUG

# logging to file
logging.file.name=logs/supply_web_service.log
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.file-name-pattern=logs/supply_web_service-%d{yyyy-MM-dd}.%i.log.gz